fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    create_resources: "git://github.com/puppetlabs/puppetlabs-create_resources.git"
  symlinks:
    dynamic_hosts: "#{source_dir}"
