name    'treydock-dynamic_hosts'
version '0.0.1'
source 'git://github.com/treydock/puppet-dynamic_hosts'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'puppet-dynamic_hosts'
description 'puppet-dynamic_hosts'
project_page 'http://github.com/treydock/puppet-dynamic_hosts'
dependency 'puppetlabs/stdlib', '>= 2.6.0'
